// 此文件由 csv/player_style.csv 自动生成，请勿直接编辑。
export type Side = 'attack' | 'defense';

export type PlayingStyle = {
  id: number;
  side: Side;
  nameZh: string;
  nameEn: string;
  positions: string[];
  descriptionZh: string;
  descriptionEn: string;
};

export const positions = ["ALL","CF","SS","LWF","RWF","AMF","LMF","RMF","CMF","DMF","LB","CB","RB","GK"] as const;

export const styles: PlayingStyle[] = [
  {
    id: 1,
    side: "attack",
    nameZh: "偷猎者",
    nameEn: "Goal Poacher",
    positions: ["CF"],
    descriptionZh: "侵略性强，善于撕开对手最后层防线的前锋。",
    descriptionEn: "A predatory striker who plays off the shoulders of the last defender.",
  },
  {
    id: 2,
    side: "attack",
    nameZh: "虚假跑位",
    nameEn: "Dummy Runner",
    positions: ["CF","SS","AMF"],
    descriptionZh: "吸引对手后卫，为其他球员创造空档的球员。",
    descriptionEn: "A player who attracts the defence to create space for other players to exploit.",
  },
  {
    id: 3,
    side: "attack",
    nameZh: "禁区之狐",
    nameEn: "Fox in the Box",
    positions: ["CF"],
    descriptionZh: "在禁区内隐藏，等待机会的前锋。",
    descriptionEn: "A striker who lurks in the opposition 18 yard box just waiting for the ball.",
  },
  {
    id: 4,
    side: "attack",
    nameZh: "站桩式中锋",
    nameEn: "Target Man",
    positions: ["CF"],
    descriptionZh: "将自己定位成在锋线的一名站桩式中锋，并以身体保护球的球员。",
    descriptionEn: "A player that positions himself on the frontlines as a target man, and protects the ball with his physique.",
  },
  {
    id: 5,
    side: "attack",
    nameZh: "组织型前锋",
    nameEn: "Deep-lying Forward",
    positions: ["CF","SS"],
    descriptionZh: "愿意回撤接球并帮助创造进攻机会的前锋球员。",
    descriptionEn: "A forward player that is willing to fall back to receive the ball and help create plays.",
  },
  {
    id: 6,
    side: "attack",
    nameZh: "有创意的中场指挥官",
    nameEn: "Creative Playmaker",
    positions: ["SS","RWF","LWF","AMF","RMF","LMF"],
    descriptionZh: "利用任何防守空当展开进攻和助攻射门的球员。",
    descriptionEn: "A player who takes advantage of any opening in the defence to initiate attacks and assists to shots on goal.",
  },
  {
    id: 7,
    side: "attack",
    nameZh: "高产翼锋",
    nameEn: "Prolific Winger",
    positions: ["RWF","LWF"],
    descriptionZh: "站在侧翼位置接收传球的球员，当机会出现时，偶尔也会切入中心。",
    descriptionEn: "A player who positions himself on the wing to receive passes, occasionally cutting into the centre when the opportunity arises.",
  },
  {
    id: 8,
    side: "attack",
    nameZh: "自由侧翼",
    nameEn: "Roaming Flank",
    positions: ["RWF","LWF","RMF","LMF"],
    descriptionZh: "倾向于从侧翼切入以接球的球员。",
    descriptionEn: "A player who tends to cut inside from the wing to receive passes.",
  },
  {
    id: 9,
    side: "attack",
    nameZh: "传中专家",
    nameEn: "Cross Specialist",
    positions: ["RWF","LWF","RMF","LMF"],
    descriptionZh: "在边线伺机横传的球员。",
    descriptionEn: "A player who hugs the touchline, waiting for a chance to cross the ball in.",
  },
  {
    id: 10,
    side: "attack",
    nameZh: "传统十号位置",
    nameEn: "Classic No. 10",
    positions: ["SS","AMF"],
    descriptionZh: "保持高位站位，方便发起攻势，伺机前插参与射门。",
    descriptionEn: "Takes a high position to initiate attacks and also goes for goal themselves when the chance arises.",
  },
  {
    id: 11,
    side: "attack",
    nameZh: "影子前锋",
    nameEn: "Hole Player",
    positions: ["SS","AMF","RMF","LMF","CMF"],
    descriptionZh: "有很大进攻欲望，一有机会就往前寻求射门的球员。",
    descriptionEn: "A player who looks to make runs into the opposition goal area when the team is on the attack.",
  },
  {
    id: 12,
    side: "attack",
    nameZh: "全能中场",
    nameEn: "Box-to-Box",
    positions: ["RMF","LMF","CMF","DMF"],
    descriptionZh: "整场比赛不懈奔跑，覆盖整个球场的球员。",
    descriptionEn: "A player who tirelessly covers every blade of grass for the full 90 minutes.",
  },
  {
    id: 13,
    side: "attack",
    nameZh: "靠山",
    nameEn: "Anchor Man",
    positions: ["DMF"],
    descriptionZh: "深入防守型中场。保护后方边线。",
    descriptionEn: "A deep sitting defensive midfielder protecting the backline.",
  },
  {
    id: 14,
    side: "attack",
    nameZh: "指挥官",
    nameEn: "Orchestrator",
    positions: ["CMF","DMF"],
    descriptionZh: "潜伏在更深的位置准备发起进攻的球员。",
    descriptionEn: "A player who lurks in deeper positions, ready to initiate attacks.",
  },
  {
    id: 15,
    side: "attack",
    nameZh: "组织大师",
    nameEn: "Build Up",
    positions: ["CB"],
    descriptionZh: "从较深位置参与进攻组织。",
    descriptionEn: "From a deep position, takes part in setting up attacks.",
  },
  {
    id: 16,
    side: "attack",
    nameZh: "额外前锋",
    nameEn: "Extra Frontman",
    positions: ["CB"],
    descriptionZh: "喜欢参与进攻，并争取每个机会围攻对手球门的后卫。",
    descriptionEn: "A defender who likes to join in the attack and lay siege on the opposition goal at every given opportunity.",
  },
  {
    id: 17,
    side: "attack",
    nameZh: "进攻型后卫",
    nameEn: "Attacking Full-back",
    positions: ["RB","LB"],
    descriptionZh: "一有机会就跑向前场参与进攻的进攻型后卫。",
    descriptionEn: "An attack-minded full-back who will run upfield and join the attack when presented with a chance.",
  },
  {
    id: 18,
    side: "attack",
    nameZh: "防守型后卫",
    nameEn: "Defensive Full-back",
    positions: ["RB","LB"],
    descriptionZh: "喜欢留在后场执行防守任务的可靠后卫。",
    descriptionEn: "A solid full-back who prefers to stay back and stick to defensive duties.",
  },
  {
    id: 19,
    side: "attack",
    nameZh: "迭瓦式终结者",
    nameEn: "Full-back Finisher",
    positions: ["RB","LB"],
    descriptionZh: "喜欢介入中心区进攻的进攻型后卫。",
    descriptionEn: "An attacking full-back who enjoys joining the attack in high central areas.",
  },
  {
    id: 20,
    side: "attack",
    nameZh: "高位防线门将",
    nameEn: "High Line GK",
    positions: ["GK"],
    descriptionZh: "进攻时保持高位站位，覆盖防线后方区域遏制反击。",
    descriptionEn: "Takes a high position when attacking, covering the area behind the defence to thwart counter attacks.",
  },
  {
    id: 21,
    side: "defense",
    nameZh: "锋线施压",
    nameEn: "Front Line Pressure",
    positions: ["CF","SS","RWF","LWF"],
    descriptionZh: "从锋线开始对门将及后卫实施高位压迫。",
    descriptionEn: "Presses the opposing keeper and defenders aggressively from the top of the front line.",
  },
  {
    id: 22,
    side: "defense",
    nameZh: "前场埋伏者",
    nameEn: "Front Line Poacher",
    positions: ["CF","SS","RWF","LWF"],
    descriptionZh: "预判对方传球路线并占据有利位置。",
    descriptionEn: "Watches the opponent's passing lanes and takes up smart positions.",
  },
  {
    id: 23,
    side: "defense",
    nameZh: "突前球员",
    nameEn: "Attack Outlet",
    positions: ["CF","SS","RWF","LWF","AMF"],
    descriptionZh: "根据局势保留体力、避免回防，始终在前场待机进攻。",
    descriptionEn: "Avoids defending to save energy depending on the situation and remains up front waiting to attack.",
  },
  {
    id: 24,
    side: "defense",
    nameZh: "全能后卫",
    nameEn: "All-action Defender",
    positions: ["AMF","RMF","LMF","CMF","DMF"],
    descriptionZh: "球队防守时积极回撤补位，应对对方攻势。",
    descriptionEn: "Runs back aggressively when the team is defending and responds to the opponent's attacks.",
  },
  {
    id: 25,
    side: "defense",
    nameZh: "传球拦截者",
    nameEn: "Pass Disruptor",
    positions: ["AMF","RMF","LMF","CMF","DMF"],
    descriptionZh: "主动封堵对方传球路线进行防守。",
    descriptionEn: "Defends by actively blocking the opponent's passing lanes.",
  },
  {
    id: 26,
    side: "defense",
    nameZh: "全能中场",
    nameEn: "Box-to-Box",
    positions: ["RMF","LMF","CMF","DMF"],
    descriptionZh: "整场比赛不懈奔跑，覆盖整个球场的球员。",
    descriptionEn: "A player who tirelessly covers every blade of grass for the full 90 minutes.",
  },
  {
    id: 27,
    side: "defense",
    nameZh: "靠山",
    nameEn: "Anchor Man",
    positions: ["DMF"],
    descriptionZh: "深入防守型中场。保护后方边线。",
    descriptionEn: "A deep sitting defensive midfielder protecting the backline.",
  },
  {
    id: 28,
    side: "defense",
    nameZh: "破坏型中场",
    nameEn: "The Destroyer",
    positions: ["CMF","DMF","RB","LB","CB"],
    descriptionZh: "通过强硬的抢球和施压阻挡对方攻击的顽强斗士。",
    descriptionEn: "Applies pressure aggressively when close to an opponent who has the ball.",
  },
  {
    id: 29,
    side: "defense",
    nameZh: "补位型球员",
    nameEn: "Covering Role",
    positions: ["CMF","DMF","RB","LB","CB"],
    descriptionZh: "主动补位进行逼迫的队友。",
    descriptionEn: "Actively covers for teammates conducting Match-up roles.",
  },
  {
    id: 30,
    side: "defense",
    nameZh: "高位防线大师",
    nameEn: "High Line Master",
    positions: ["RB","LB","CB"],
    descriptionZh: "专注于保持高效防守阵型，确保防守时整体架构稳固。",
    descriptionEn: "Looks to maintain an effective defensive line, keeping the shape intact as they defend.",
  },
  {
    id: 31,
    side: "defense",
    nameZh: "进攻型守门员",
    nameEn: "Attacking GK",
    positions: ["GK"],
    descriptionZh: "果断出击封锁射门角度，应对传到防线后方的球。",
    descriptionEn: "Comes out aggressively to limit shooting angles and respond to balls sent behind the defence.",
  },
  {
    id: 32,
    side: "defense",
    nameZh: "防守型守门员",
    nameEn: "Defensive GK",
    positions: ["GK"],
    descriptionZh: "固守球门附近区域，避免贸然出击。",
    descriptionEn: "Holds a position near the goal and refrains from rushing out aggressively.",
  },
  {
    id: 33,
    side: "defense",
    nameZh: "清道夫门将",
    nameEn: "Sweeper GK",
    positions: ["GK"],
    descriptionZh: "采取高位站位，迅猛出击覆盖防线后方广阔区域。",
    descriptionEn: "Takes a high position and rushes out aggressively to cover a wide area behind the defence.",
  },
];
