// 此文件由 csv/player_skill.csv 自动生成，请勿直接编辑。
export const skillCategories = [
  { id: 'all', label: '全部', nameEn: 'All' },
  { id: "Showtime", label: "ST技能", nameEn: "Showtime" },
  { id: "Shooting", label: "射门", nameEn: "Shooting" },
  { id: "Dribbling", label: "盘带", nameEn: "Dribbling" },
  { id: "Passing", label: "传球", nameEn: "Passing" },
  { id: "Defending", label: "防守", nameEn: "Defending" },
  { id: "Goalkeeping", label: "守门", nameEn: "Goalkeeping" },
  { id: "Other", label: "其他", nameEn: "Other" },
] as const;

export type SkillCategory = Exclude<(typeof skillCategories)[number]['id'], 'all'>;

export type PlayerSkill = {
  id: number;
  nameZh: string;
  nameEn: string;
  description: string;
  descriptionEn: string;
  researchZh?: string;
  researchEn?: string;
  categories: SkillCategory[];
  image: string;
};

export const playerSkills: PlayerSkill[] = [
  { id: 1, nameZh: "剪刀脚假动作", nameEn: "Scissors Feint", description: "输入假动作指令时执行剪刀脚假动作。", descriptionEn: "Performs a Scissors Feint when entering a feint command.", categories: ["Dribbling"], image: "/skills/01.png" },
  { id: 2, nameZh: "两次触球", nameEn: "Double Touch", description: "输入假动作指令时执行两次触球。", descriptionEn: "Performs a Double Touch when entering a feint command.", categories: ["Dribbling"], image: "/skills/02.png" },
  { id: 3, nameZh: "牛摆尾", nameEn: "Flip Flap", description: "输入假动作指令时执行牛摆尾。", descriptionEn: "Performs a Flip Flap when entering a feint command.", categories: ["Dribbling"], image: "/skills/03.png" },
  { id: 4, nameZh: "马赛回旋", nameEn: "Marseille Turn", description: "输入假动作指令时执行马赛回旋。", descriptionEn: "Performs a Marseille Turn when entering a feint command.", categories: ["Dribbling"], image: "/skills/04.png" },
  { id: 5, nameZh: "挑球过顶", nameEn: "Sombrero", description: "提升挑球过顶和彩虹过人的精准度；接地面传球时也可施展挑球过顶。", descriptionEn: "Increases the accuracy of Sombrero and Rainbow Flick. Also allows the player to perform a Sombrero when receiving a Low Pass.", categories: ["Dribbling"], image: "/skills/05.png" },
  { id: 6, nameZh: "脚后跟磕球变向", nameEn: "Chop Turn", description: "输入假动作指令时执行脚后跟磕球变向。", descriptionEn: "Performs a Chop Turn when entering a feint command.", categories: ["Dribbling"], image: "/skills/06.png" },
  { id: 7, nameZh: "向后切球并转身", nameEn: "Cut Behind & Turn", description: "执行向后切球；大角度转身时还会使用特殊停球动作。", descriptionEn: "Performs a Cut Behind. When turning at a wide angle, also uses a special trapping motion.", categories: ["Dribbling"], image: "/skills/07.png" },
  { id: 8, nameZh: "磕球过人", nameEn: "Scotch Move", description: "输入假动作指令时执行磕球过人。", descriptionEn: "Performs a Scotch Move when entering a feint command.", categories: ["Dribbling"], image: "/skills/08.png" },
  { id: 9, nameZh: "后脚磕球变向", nameEn: "Tap Trick", description: "输入假动作指令时执行后脚磕球变向假动作。", descriptionEn: "Performs a Tap Trick feint when entering a feint command.", categories: ["Showtime"], image: "/skills/09.png" },
  { id: 10, nameZh: "足底控球", nameEn: "Sole Control", description: "使球员在做假动作和转身时更多地用脚掌控球。", descriptionEn: "Enables the player to control the ball more using the soles of his feet when executing feints and turns.", categories: ["Dribbling"], image: "/skills/10.png" },
  { id: 11, nameZh: "旋风盘带", nameEn: "Momentum Dribbling", description: "提高球员在进攻三区的盘球能力。", descriptionEn: "Improves player's dribbling abilities in the attacking third (deep in opposition territory).", categories: ["Showtime"], image: "/skills/11.png" },
  { id: 12, nameZh: "瞬间加速", nameEn: "Acceleration Burst", description: "可在静止或缓慢移动时快速施展锐钻触球，也可能触发特殊锐钻触球动作。", descriptionEn: "Enables the player to perform a quick Sharp Touch while stationary or moving slowly. Special Sharp Touch motions may also be triggered.", categories: ["Showtime"], image: "/skills/12.png" },
  { id: 13, nameZh: "磁力脚", nameEn: "Magnetic Feet", description: "控球时，根据 5 米范围内对手人数（最多 4 人）提高控球能力。", descriptionEn: "When in possession of the ball, increases the player's ability to keep it based on the number of opponents within 5 metres (4 opponents max).", categories: ["Showtime"], image: "/skills/13.png" },
  { id: 14, nameZh: "头球", nameEn: "Heading", description: "提高头球精准度和砸地头球的频度。", descriptionEn: "Improves the accuracy of headers as well as the frequency of downward headers.", categories: ["Other"], image: "/skills/14.png" },
  { id: 15, nameZh: "炮弹式头球", nameEn: "Bullet Header", description: "可完成势大力沉的头球攻门，姿势不自然或失去平衡时也更容易完成。", descriptionEn: "Enables the player to head the ball sharply towards goal, shooting with power and accuracy even from awkward positions or when off balance.", categories: ["Showtime"], image: "/skills/15.png" },
  { id: 16, nameZh: "远距离弧线球", nameEn: "Long-range Curler", description: "远距离施展大弧度且精准的控制射门。", descriptionEn: "Performs a sharp, accurate Controlled Shot with a heavy curl that often hits the target even from a long distance.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全部技能研究：射门篇》（BV1aadcYKE9X）：\n\n1、对搓射时的球速、精准度和弧度都有提升，提升效果等效脚力值和射门值+10%多一点。在禁区内外都会生效。\n2、搓射不受远射加成。\n3、远距离弧线球是改参数技能，不是加能力值技能，所以可以突破能力上限而不怕溢出浪费，同时也可以弥补逆足带来的debuff。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Shooting\" (BV1aadcYKE9X):\n\n1. For curl shots, including Blitz Curler shots, ball speed, accuracy, and curl are all improved. The effect is equivalent to adding slightly more than 10% to Kicking Power and Shooting Ability, and it takes effect both inside and outside the penalty area.\n2. Curl shots, including Blitz Curler shots, are not affected by Long-range Shooting.\n3. Long-range Curler is a parameter-adjustment skill rather than an Ability increase, so it can exceed the Ability limit without wasting the excess, and it can also offset the debuff from using the weaker foot.", categories: ["Shooting"], image: "/skills/16.png" },
  { id: 17, nameZh: "弧线落叶射门", nameEn: "Blitz Curler", description: "力量槽至少 50% 时，可施展带强烈上旋的控制射门。", descriptionEn: "Performs a Controlled Shot with heavy topspin while the Power Gauge is at least 50% full.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全部技能研究：射门篇》（BV1aadcYKE9X）：\n\n1、球速比普通搓射快一点，约1.2%\n2、射门落点是瞄准侧上方死角的，这就是弧线落叶射门球路能吊过门将的奥秘\n3、受【远距离弧线球】技能的加成\n4、逆足精度最高级“非常高”即可用逆足触发弧线落叶射门\n5、对外脚背弧线球控制射门无影响，即使有外脚背弧线球技能也可以通过进一步再搓来进行逆足弧线落叶射门。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Shooting\" (BV1aadcYKE9X):\n\n1. Ball speed is slightly faster than a normal curl shot, by about 1.2%.\n2. The shot aims at the upper side-corner of the goal; this is the secret behind the Blitz Curler trajectory being able to clear the goalkeeper.\n3. It benefits from the Long-range Curler skill.\n4. A weaker-foot accuracy level of “Very High”, the highest level, is enough to trigger Blitz Curler with the weaker foot.\n5. Outside Curler control shots are unaffected; even with Outside Curler, the player can curl again to perform a weaker-foot Blitz Curler shot.", categories: ["Showtime"], image: "/skills/17.png" },
  { id: 18, nameZh: "吊射控制", nameEn: "Chip Shot Control", description: "高速移动时也能精准吊射。", descriptionEn: "Performs an accurate Chip Shot, even when moving at high speed.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全部技能研究：射门篇》（BV1aadcYKE9X）：\n\n让吊射球路更高更“陡峭”，有助于越过出击的门将。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Shooting\" (BV1aadcYKE9X):\n\nMakes the Chip Shot trajectory higher and more “steep”, helping it clear an advancing goalkeeper.", categories: ["Shooting"], image: "/skills/18.png" },
  { id: 19, nameZh: "落叶球射门", nameEn: "Knuckle Shot", description: "力量槽达到 50%–65% 时，以惊人射门指令踢出电梯球；也适合任意球。", descriptionEn: "Performs a Knuckle Shot when entering a Stunning Shot command while the Power Gauge is 50-65% full. A good free kick option.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全部技能研究：射门篇》（BV1aadcYKE9X）：\n\n1、球路：落叶球射门左右飘忽；急坠射门竖直方向下坠而不侧向漂移；急升射门球路持续上升。\n2、球速：三种特殊球技能，球速均和同情况下紫射一样。\n3、进球率：同情景下，急坠射门比普通紫射进球率高32%，因为球路稳，无侧弧线，不易偏出；落叶球射门比普通紫射进球率高14%；急升射门比普通紫射进球率低11%，因为球路容易太高、太偏。\n4、任意球：落叶球射门、急坠射门可在任意球触发，急坠射门任意球实战价值大。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Shooting\" (BV1aadcYKE9X):\n\n1. Trajectory: Knuckle Shot moves unpredictably from side to side; Dipping Shot drops vertically without drifting sideways; Rising Shot continues to rise.\n2. Ball speed: For all three special-shot skills, ball speed is the same as a purple shot in the same situation.\n3. Conversion rate: In the same situation, Dipping Shot has a 32% higher conversion rate than a normal purple shot because its trajectory is stable, has no side curl, and is less likely to miss; Knuckle Shot has a 14% higher conversion rate; Rising Shot has an 11% lower conversion rate because its trajectory can be too high and too wide.\n4. Free kicks: Knuckle Shot and Dipping Shot can be triggered on free kicks, and Dipping Shot has high practical value on free kicks.", categories: ["Shooting"], image: "/skills/19.png" },
  { id: 20, nameZh: "急坠射门", nameEn: "Dipping Shot", description: "力量槽达到 20%–50% 时，以惊人射门指令踢出急坠射门。", descriptionEn: "Performs a Dipping Shot when entering a Stunning Shot command while the Power Gauge is 20-50% full.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全部技能研究：射门篇》（BV1aadcYKE9X）：\n\n1、球路：落叶球射门左右飘忽；急坠射门竖直方向下坠而不侧向漂移；急升射门球路持续上升。\n2、球速：三种特殊球技能，球速均和同情况下紫射一样。\n3、进球率：同情景下，急坠射门比普通紫射进球率高32%，因为球路稳，无侧弧线，不易偏出；落叶球射门比普通紫射进球率高14%；急升射门比普通紫射进球率低11%，因为球路容易太高、太偏。\n4、任意球：落叶球射门、急坠射门可在任意球触发，急坠射门任意球实战价值大。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Shooting\" (BV1aadcYKE9X):\n\n1. Trajectory: Knuckle Shot moves unpredictably from side to side; Dipping Shot drops vertically without drifting sideways; Rising Shot continues to rise.\n2. Ball speed: For all three special-shot skills, ball speed is the same as a purple shot in the same situation.\n3. Conversion rate: In the same situation, Dipping Shot has a 32% higher conversion rate than a normal purple shot because its trajectory is stable, has no side curl, and is less likely to miss; Knuckle Shot has a 14% higher conversion rate; Rising Shot has an 11% lower conversion rate because its trajectory can be too high and too wide.\n4. Free kicks: Knuckle Shot and Dipping Shot can be triggered on free kicks, and Dipping Shot has high practical value on free kicks.", categories: ["Shooting"], image: "/skills/20.png" },
  { id: 21, nameZh: "急升射门", nameEn: "Rising Shot", description: "力量槽达到 65%–95% 时，以惊人射门指令踢出上升射门。", descriptionEn: "Performs a Rising Shot when entering a Stunning Shot command while the Power Gauge is 65-95% full.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全部技能研究：射门篇》（BV1aadcYKE9X）：\n\n1、球路：落叶球射门左右飘忽；急坠射门竖直方向下坠而不侧向漂移；急升射门球路持续上升。\n2、球速：三种特殊球技能，球速均和同情况下紫射一样。\n3、进球率：同情景下，急坠射门比普通紫射进球率高32%，因为球路稳，无侧弧线，不易偏出；落叶球射门比普通紫射进球率高14%；急升射门比普通紫射进球率低11%，因为球路容易太高、太偏。\n4、任意球：落叶球射门、急坠射门可在任意球触发，急坠射门任意球实战价值大。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Shooting\" (BV1aadcYKE9X):\n\n1. Trajectory: Knuckle Shot moves unpredictably from side to side; Dipping Shot drops vertically without drifting sideways; Rising Shot continues to rise.\n2. Ball speed: For all three special-shot skills, ball speed is the same as a purple shot in the same situation.\n3. Conversion rate: In the same situation, Dipping Shot has a 32% higher conversion rate than a normal purple shot because its trajectory is stable, has no side curl, and is less likely to miss; Knuckle Shot has a 14% higher conversion rate; Rising Shot has an 11% lower conversion rate because its trajectory can be too high and too wide.\n4. Free kicks: Knuckle Shot and Dipping Shot can be triggered on free kicks, and Dipping Shot has high practical value on free kicks.", categories: ["Shooting"], image: "/skills/21.png" },
  { id: 22, nameZh: "远射", nameEn: "Long-range Shooting", description: "从禁区外射出更容易命中目标的远射。", descriptionEn: "Performs a Long-range Shot from outside the box that often hits the target.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全部技能研究：射门篇》（BV1aadcYKE9X）：\n\n1、远射起效时会让射门能力值+10%；但不会加成脚下力量（而逆足也不影响脚下力量）\n2、远射是纯加能力值，+10%后超过上限的部分不会生效。\n3、远射这类纯加能力技能，计算顺序先于逆足debuff，不会因为用逆足而让溢出的能力值变得有意义，但体能少于50%时溢出部分就有用。\n4、远射技能生效的界限就是大禁区外。\n5、远射技能对远距离弧线球（搓射）没有加成作用，但对紫射有加成。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Shooting\" (BV1aadcYKE9X):\n\n1. When Long-range Shooting takes effect, it increases Shooting Ability by +10%, but does not increase Kicking Power (and using the weaker foot does not affect Kicking Power).\n2. Long-range Shooting is a pure Ability increase; any portion above the limit after the +10% increase does not take effect.\n3. For this type of pure Ability increase, the calculation comes before the weaker-foot debuff. Using the weaker foot does not make the excess Ability meaningful, but when Stamina is below 50%, the excess portion is useful.\n4. Long-range Shooting takes effect outside the penalty area.\n5. Long-range Shooting does not increase Long-range Curler (curl shots), but it does increase purple shots.", categories: ["Shooting"], image: "/skills/22.png" },
  { id: 23, nameZh: "掠地瞬击", nameEn: "Low Screamer", description: "力量槽低于 50% 的惊人射门球速提升，且不会出现急坠射门。", descriptionEn: "Performing a Stunning Shot while the Power Gauge is under 50% full will increase the speed of the shot. A Dipping Shot will not occur.", categories: ["Showtime"], image: "/skills/23.png" },
  { id: 24, nameZh: "瞬发射门", nameEn: "Snap Strike", description: "缩短惊人射门的出脚时间。", descriptionEn: "Takes less time to kick the ball when making a Stunning Shot.", categories: ["Showtime"], image: "/skills/24.png" },
  { id: 25, nameZh: "杂技般进球", nameEn: "Acrobatic Finishing", description: "在不自然姿势或失去平衡时也能找到射门机会。", descriptionEn: "Enables the player to find a finish even from awkward positions or when off balance.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全部技能研究：射门篇》（BV1aadcYKE9X）：\n\n1、提升触发射门动作的判定范围，例如各种侧倒射门。\n2、增加非常规的射门动作。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Shooting\" (BV1aadcYKE9X):\n\n1. Increases the judgment range for triggering shooting animations, such as various side-falling shots.\n2. Adds unconventional shooting animations.", categories: ["Shooting"], image: "/skills/25.png" },
  { id: 26, nameZh: "脚跟绝技", nameEn: "Heel Trick", description: "在不自然姿势或失去平衡时也能用脚后跟传球或射门。", descriptionEn: "Enables the player to pass and shoot using the heel, even from awkward positions or when off balance.", categories: ["Passing"], image: "/skills/26.png" },
  { id: 27, nameZh: "一脚射门", nameEn: "First-time Shot", description: "提高第一时间射门的技术和精准度。", descriptionEn: "Improves technique and precision when taking first- time shots.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全部技能研究：射门篇》（BV1aadcYKE9X）：\n\n1、机制：减少不停球直接射门的射门质量debuff\n2、对精准度和球速均有帮助\n3、即使再缓慢、稳定的来球，有【一脚射门】都会带来明显的射门质量提升\n4、即使有【一脚射门】，面对不好处理的高速或弹跳来球，都会出现明显的射门质量下降。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Shooting\" (BV1aadcYKE9X):\n\n1. Mechanism: Reduces the shot-quality debuff on direct shots without controlling the ball first.\n2. Helps both accuracy and ball speed.\n3. Even with a slow, stable incoming ball, First-time Shot provides a clear improvement in shot quality.\n4. Even with First-time Shot, a difficult high-speed or bouncing incoming ball still causes a clear decline in shot quality.", categories: ["Shooting"], image: "/skills/27.png" },
  { id: 28, nameZh: "无定型射门", nameEn: "Phenomenal Finishing", description: "提高不自然身体姿势下射门的力量和精准度。", descriptionEn: "Increases the power and accuracy of finishing shots attempted from unorthodox body positions.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全部技能研究：射门篇》（BV1aadcYKE9X）：\n\n1、大角度转身/姿态别扭/凌空/飞身侧勾射门会被判定为失衡状态，射门质量会有debuff。而无定型射门则是减轻这种debuff。\n2、成熟的应用套路是：接球转身推远角。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Shooting\" (BV1aadcYKE9X):\n\n1. Large-angle turns, awkward body posture, volleys, and flying side volleys may be judged as unbalanced states, causing a shot-quality debuff. Phenomenal Finishing reduces this debuff.\n2. A mature application is to receive the ball, turn, and push the shot toward the far corner.", categories: ["Showtime"], image: "/skills/28.png" },
  { id: 29, nameZh: "百折不挠", nameEn: "Willpower", description: "每次射门可提升射门能力，最多累积 8 次。", descriptionEn: "Improves player's shooting abilities whenever they take a shot, up to a maximum of 8 times.", categories: ["Showtime"], image: "/skills/29.png" },
  { id: 30, nameZh: "一脚传球", nameEn: "One-touch Pass", description: "提高一脚传球的技术和精准度。", descriptionEn: "Improves technique and precision when executing one- touch passes.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全技能真实效果研究：传球篇》（BV1do4y1K7A1）：\n\n1、单触是【改参数】技能，大幅减少一脚出球的debuff。\n2、越是球路不稳定、快速的来球，一脚出球debuff越大，越需要单触。来球球路差（蹦蹦跳跳）时，单触能起到超过几十点传球值的效果。\n3、球队的传递过程中，有单触球员和传球大师很重要，若来球球路稳定（贴地球+别太快），没有单触的前场球员也能处理好一脚出球。\n4、单触对地传和空传都有用，一脚空传其实更需要单触。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Passing\" (BV1do4y1K7A1):\n\n1. One-touch Pass reduces the debuff on a first-time pass and is a parameter-adjustment skill.\n2. The more unstable the ball path and the faster the incoming ball, the larger the first-time-pass debuff and the more One-touch Pass is needed. When the incoming ball has a poor path (bouncing around), One-touch Pass can have an effect worth more than several dozen passing points.\n3. In team passing, players with One-touch Pass and the Passing Maestro are important. If the incoming ball path is stable (a grounded ball and not too fast), a forward without One-touch Pass can also handle the first-time pass.\n4. One-touch Pass helps both ground passes and lofted passes; a first-time lofted pass needs it even more.", categories: ["Passing","Goalkeeping"], image: "/skills/30.png" },
  { id: 31, nameZh: "直传球", nameEn: "Through Passing", description: "可传出轨迹合适的直塞球，并提高整体直塞精准度。", descriptionEn: "Enables the player to make through passes with the appropriate trajectory. Also improves the overall accuracy of through passes.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全技能真实效果研究：传球篇》（BV1do4y1K7A1）：\n\n1、直传球技能会对直塞和过顶直塞都有加成\n2、普通直塞看的是地面传球能力，过顶直塞看的是空中传球能力\n3、直传球技能属于【加能力】而不是【改参数】，会对相应的传球能力加 20%（仅限在直传时，普通传球不受加成）", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Passing\" (BV1do4y1K7A1):\n\n1. Through Passing improves both through passes and lofted through passes.\n2. Normal through passes rely on Ground Pass, while lofted through passes rely on Lofted Pass.\n3. Through Passing is an Ability-increase skill rather than a parameter-adjustment skill. It increases the corresponding passing Ability by 20% (only for through passes; normal passes receive no bonus).", categories: ["Passing","Goalkeeping"], image: "/skills/31.png" },
  { id: 32, nameZh: "精准长传", nameEn: "Weighted Pass", description: "向前方踢出带强烈后旋的精准高空传球或挑传直塞。", descriptionEn: "Performs an accurate Lofted Pass or Chipped Through Ball with heavy backspin to a forward area.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全技能真实效果研究：传球篇》（BV1do4y1K7A1）：\n\n1、精准长传是【改参数】技能，让空传球路先平后陡，并不是直接加长传能力，以前的翻译加重旋转传球更合适。\n2、此技能在后场更容易触发，用长传和过顶直塞都会触发，过顶直塞更容易触发。紫传、传中不触发。\n3、用长传触发技能后，球路更合适身材高、弹跳好的球员发挥争顶优势；球路后段减速技能也有利于空传分边后的接球。但会整体上会明显减慢球速，拖慢进攻节奏。\n4、触发后长传的提前量更小，落点更靠近球员。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Passing\" (BV1do4y1K7A1):\n\n1. Weighted Pass is a parameter-adjustment skill. It makes the lofted-pass trajectory travel flat first and then rise, rather than directly increasing Lofted Pass Ability. The previous translation, “weighted spin pass”, is more appropriate.\n2. This skill is easier to trigger in the defensive half. Long passes and lofted through passes can trigger it, with lofted through passes being easier to trigger. Purple passes and crosses do not trigger it.\n3. After triggering it with a long pass, the trajectory is more suitable for tall players with good jumping ability to contest the ball. The late-trajectory deceleration also helps receive a lofted pass played out wide, but it noticeably slows the ball and the attacking tempo overall.\n4. After triggering, the lead on a long pass is smaller and the landing point is closer to the player.", categories: ["Passing","Defending","Goalkeeping"], image: "/skills/32.png" },
  { id: 33, nameZh: "精确横传球", nameEn: "Pinpoint Crossing", description: "踢出带明显弧线的快速精准传中。", descriptionEn: "Performs a sharp, accurate cross with a heavy curl.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全技能真实效果研究：传球篇》（BV1do4y1K7A1）：\n\n1、精确横传球对地面横传和空中横传都有相应传球值的加成，而地面横传看地传值、空中横传看空传值。\n2、精确横传球是【加能力】类型技能，会加成传球值10%（仅限传中时，普通长传不受加成）\n3、精确横传球不会影响弧线球能力", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Passing\" (BV1do4y1K7A1):\n\n1. Pinpoint Crossing increases the relevant passing value for both ground crosses and lofted crosses. Ground crosses use Ground Pass value, while lofted crosses use Lofted Pass value.\n2. Pinpoint Crossing is an Ability-increase skill and increases Passing value by 10% (only for crosses; normal long passes receive no bonus).\n3. Pinpoint Crossing does not affect Curl.", categories: ["Passing"], image: "/skills/33.png" },
  { id: 34, nameZh: "急坠传中", nameEn: "Edged Crossing", description: "踢出垂直旋转且急速下坠的传中球。", descriptionEn: "Enables the player to put in vertically rotating crosses that fall sharply.", categories: ["Showtime"], image: "/skills/34.png" },
  { id: 35, nameZh: "外脚背弧线球", nameEn: "Outside Curler", description: "用较强脚的外侧踢出精准的旋转射门或传球，远距离也适用。", descriptionEn: "Performs a precise spinning shot or pass with the outside of the boot, even from range, using the stronger foot for accuracy.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全部技能研究：射门篇》（BV1aadcYKE9X）：\n\n外脚背弧线球：射门篇——\n1、触发：有外脚背弧线球技能即可在输入控制射门时，把大多数逆足搓射变为外脚背弧线球射门。触发与逆足频率无关。用平行底线趟球后再搓的方式可以在有外脚背弧线球技能情况下触发逆足搓射/逆足弧线落叶射门。\n2、外脚背弧线球射门不受远距离弧线球加成，也不受弧线落叶射门技能影响球路。\n3、有远距离弧线球的对比下，外脚背弧线球射门球速比搓射慢9%，弧线持平，但精准度比搓射强，且球路更低适合禁区内使用。\n4、外脚背弧线球的优势是比逆足踢球更快出脚（射门时快3帧）。\n外脚背弧线球：传球篇——\n1、触发：无主动输入手段，需有外脚背弧线球技能，出球方向是面朝方向往顺足侧偏30°～60°左右。触发与逆足频率无关。\n2、外脚背弧线球空传：球速比普通传略快，弧线比普通传更大。外脚背弧线球传中需要较近距离才能触发。\n3、外脚背弧线球地传：球速不是优势，弧线比普通传更大，球路能保证稳定、贴地。\n4、外脚背弧线球射门传球的共同优势是比逆足踢球更快出脚。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Shooting\" (BV1aadcYKE9X):\n\nOutside Curler: Shooting —\n1. Trigger: With Outside Curler, entering a controlled shot turns most weaker-foot curl shots into Outside Curler shots. Triggering is unrelated to weaker-foot frequency. After carrying the ball parallel to the touchline, curling the shot can trigger a weaker-foot curl shot or a weaker-foot Blitz Curler shot when Outside Curler is available.\n2. Outside Curler shots are not affected by Long-range Curler and their trajectory is not affected by Blitz Curler.\n3. Compared with Long-range Curler shots, Outside Curler shots are 9% slower, have the same amount of curl, but are more accurate and have a lower trajectory, making them suitable for use inside the penalty area.\n4. The advantage of Outside Curler is that it releases faster than a weaker-foot shot (3 frames faster when shooting).\n\nOutside Curler: Passing —\n1. Trigger: There is no active input method. Outside Curler is required, and the ball travels about 30°–60° toward the strong-foot side relative to the facing direction. Triggering is unrelated to weaker-foot frequency.\n2. Outside Curler lofted passes are slightly faster than normal passes and have more curl. Outside Curler crosses require a relatively short distance to trigger.\n3. Outside Curler ground passes have no speed advantage, but have more curl than normal passes and maintain a stable, grounded trajectory.\n4. The shared advantage of Outside Curler shots and passes is a faster release than weaker-foot kicks.", categories: ["Passing"], image: "/skills/35.png" },
  { id: 36, nameZh: "插花脚", nameEn: "Rabona", description: "用较强脚施展出其不意的插花脚，扰乱防守节奏。", descriptionEn: "Performs a Rabona to disrupt the defence's timing with a surprise kick, using the stronger foot for accuracy.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全部技能研究：射门篇》（BV1aadcYKE9X）：\n\n（能触发插花脚传球/射门/花式）\n1、插花脚传球的触发需传球目标距离适当不能太长，角度与前进方向成90°～120°，以空传触发（实战中概率很低）。它的球路较低且无弧线，球速无劣势。\n2、插花脚射门需要超过近距离射门才会出现，插花脚射门和传球都是逆足频率越低越大概率触发。\n3、插花脚技能的主要意义在插花脚假射急停，这种急停比一般假射急停入球结合更好，后续动作衔接得快很多（约8帧优势）。触发需要运动方向大致垂直于人与球门连线，逆足频率为经常则可以双腿均触发。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Shooting\" (BV1aadcYKE9X):\n\n(Can trigger Rabona passes, shots, and skills)\n1. A Rabona pass requires the target distance to be appropriate and not too long, with an angle of 90°–120° relative to the movement direction. It is triggered with a lofted pass (very unlikely in actual matches). Its trajectory is relatively low with no curl, and it has no speed disadvantage.\n2. A Rabona shot only appears beyond close-range shooting distance. Both Rabona shots and passes are more likely to trigger when weaker-foot frequency is lower.\n3. The main purpose of Rabona is the Rabona fake-shot stop. This stop combines better with the ball than a normal fake-shot stop, and subsequent actions connect much faster (about an 8-frame advantage). Triggering requires the movement direction to be roughly perpendicular to the line between the player and the goal; when weaker-foot frequency is frequent, both legs can trigger it.", categories: ["Passing"], image: "/skills/36.png" },
  { id: 37, nameZh: "不看球员传球", nameEn: "No Look Pass", description: "以视线迷惑对手，送出意想不到的传球。", descriptionEn: "Enables the player to play unexpected passes and confuse the opponent with his lines of sight.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全技能真实效果研究：传球篇》（BV1do4y1K7A1）：\n\n1、主要是直传球的时候触发的头部动作，短传一般不触发。而且是直塞给空挡很大的队友，成功率很高的时候触发的耍帅动作。如果直塞难度很大则一般不会触发\n2、观察不到对对方后防ai的明显影响\n3、观察不到对尴尬身位出球的改善", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Passing\" (BV1do4y1K7A1):\n\n1. It is mainly a head animation triggered during a through pass and generally does not trigger on short passes. It is more likely to trigger a stylish animation when the through pass is played to a teammate with a large amount of space and a high success rate. If the through pass is very difficult, it generally does not trigger.\n2. No obvious effect on the opposing defensive AI can be observed.\n3. No improvement in passing from awkward body positions can be observed.", categories: ["Passing"], image: "/skills/37.png" },
  { id: 38, nameZh: "翻盘传球", nameEn: "Game-changing Pass", description: "下半场球队平局或落后时，提高传球能力。", descriptionEn: "Improves player's passing abilities after the second half kick-off, under the circumstances that the team is either drawing or losing.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全技能真实效果研究：传球篇》（BV1do4y1K7A1）：\n\n下半场打平或落后时，地传和空传+10%（由于此加成适用于任何传球而不是特定种类的传球，故其效果还是比直传球、精准横传更强）", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Passing\" (BV1do4y1K7A1):\n\nWhen the match is level or the team is trailing in the second half, Ground Pass and Lofted Pass receive +10%. Since this bonus applies to all passes rather than a specific type of pass, its effect is still stronger than Through Passing and Pinpoint Crossing.", categories: ["Showtime"], image: "/skills/38.png" },
  { id: 39, nameZh: "到位传球", nameEn: "Visionary Pass", description: "提高接球队友的一脚传球、直接射门和停球精准度。", descriptionEn: "Increases the accuracy of one-touch passes, first-time shots and traps performed by players who receive passes from the holder of this Player Skill.", categories: ["Showtime"], image: "/skills/39.png" },
  { id: 40, nameZh: "无定型传球", nameEn: "Phenomenal Pass", description: "提高不自然身体姿势下传球的力量和精准度。", descriptionEn: "Increases the power and accuracy of passes attempted from unorthodox body positions.", categories: ["Showtime"], image: "/skills/40.png" },
  { id: 41, nameZh: "低空传球", nameEn: "Low Lofted Pass", description: "踢出低轨迹、距离远且精准的高空传球。", descriptionEn: "Enables the player to hit long and accurate Lofted Passes with a low trajectory.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全技能真实效果研究：传球篇》（BV1do4y1K7A1）：\n\n1、是改参数技能，会踢出更低轨迹的球路。\n2、触发条件：任何普通长传都会100%触发，但是传中和过顶直塞不触发。\n3、低空传球的球路比普通球路要稍微低一点。低空传球会有微弱的球速优势和精准度优势。", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Passing\" (BV1do4y1K7A1):\n\n1. Low Lofted Pass is a parameter-adjustment skill and produces a lower trajectory.\n2. Trigger condition: Any normal long pass triggers it 100%, but crosses and lofted through passes do not trigger it.\n3. The trajectory of Low Lofted Pass is slightly lower than a normal trajectory, with slight advantages in ball speed and accuracy.", categories: ["Passing","Goalkeeping"], image: "/skills/41.png" },
  { id: 42, nameZh: "守门员低弹道凌空球", nameEn: "GK Low Punt", description: "守门员可踢出精准的低弹道凌空球。", descriptionEn: "Enables the player to take accurate punt kicks with a low trajectory.", categories: ["Goalkeeping"], image: "/skills/42.png" },
  { id: 43, nameZh: "守门员高弹道凌空球", nameEn: "GK High Punt", description: "守门员可踢出长距离高轨迹开球，深入对方半场。", descriptionEn: "Enables goalkeepers to take long, high punt kicks that end up deep in opposition territory.", categories: ["Goalkeeping"], image: "/skills/43.png" },
  { id: 44, nameZh: "长距离投掷", nameEn: "Long Throw", description: "增加界外球投掷距离。", descriptionEn: "Improves the range of long throws.", researchZh: "研究结果 from 珠海amadeusz，对应资料：视频《全技能真实效果研究：传球篇》（BV1do4y1K7A1）：\n\n界外球最大投掷距离（落地点）从21m升高到28m", researchEn: "Research results from 珠海amadeusz, source: video \"All Skills Research: Passing\" (BV1do4y1K7A1):\n\nThe maximum throw-in distance, measured at the landing point, increases from 21 m to 28 m.", categories: ["Other"], image: "/skills/44.png" },
  { id: 45, nameZh: "守门员长距离投掷", nameEn: "GK Long Throw", description: "增加守门员手抛球距离。", descriptionEn: "Improves the range on throws by the goalkeeper.", categories: ["Goalkeeping"], image: "/skills/45.png" },
  { id: 46, nameZh: "点球专家", nameEn: "Penalty Specialist", description: "提高主罚点球的精准度。", descriptionEn: "Enables the player to take higher accuracy penalty kicks.", categories: ["Shooting","Other"], image: "/skills/46.png" },
  { id: 47, nameZh: "守门员扑点球", nameEn: "GK Penalty Saver", description: "提高守门员应对点球时的反应。", descriptionEn: "Enables the player to have better goalkeeping reactions against penalty kicks.", categories: ["Goalkeeping"], image: "/skills/47.png" },
  { id: 48, nameZh: "守门员指挥防守", nameEn: "GK Directing Defence", description: "提高己方腹地后卫的防守能力。", descriptionEn: "Goalkeeper Skill that improves the defensive abilities of your DF players positioned deep in your own territory.", categories: ["Showtime"], image: "/skills/48.png" },
  { id: 49, nameZh: "门神战吼", nameEn: "GK Spirit Roar", description: "下半场领先时，提高己方后卫的身体能力。", descriptionEn: "Goalkeeper Skill that improves the physical abilities of your DF players when leading after half-time.", categories: ["Showtime"], image: "/skills/49.png" },
  { id: 50, nameZh: "假摔", nameEn: "Gamesmanship", description: "控球时更容易赢得犯规。", descriptionEn: "Wins fouls more easily when in possession of the ball.", categories: ["Other"], image: "/skills/50.png" },
  { id: 51, nameZh: "盯人", nameEn: "Man Marking", description: "快速反应对手动作，施加紧密盯防。", descriptionEn: "Reacts quickly to an opponent's movements and applies tight marking that is hard to shake.", categories: ["Defending"], image: "/skills/51.png" },
  { id: 52, nameZh: "压迫", nameEn: "Track Back", description: "从前线开始积极压迫对方持球球员。", descriptionEn: "Enables the player to aggressively apply pressure to the opposition ballholder all the way from the frontlines.", categories: ["Defending"], image: "/skills/52.png" },
  { id: 53, nameZh: "截球", nameEn: "Interception", description: "更快地对传球作出反应，提高拦截成功率。", descriptionEn: "Reacts quickly to passes and intercepts them at a higher rate.", categories: ["Defending"], image: "/skills/53.png" },
  { id: 54, nameZh: "封堵", nameEn: "Blocker", description: "更快封堵传球和射门，并减少反弹球。", descriptionEn: "Reacts quickly to kicks by blocking passes and shots at a high rate, and also limits the amount of rebound.", categories: ["Defending"], image: "/skills/54.png" },
  { id: 55, nameZh: "空中优势", nameEn: "Aerial Superiority", description: "空中争抢更占优势，更容易保持头球精准度。", descriptionEn: "Gains an advantage during mid-air battles and maintains heading accuracy more easily.", categories: ["Defending","Other"], image: "/skills/55.png" },
  { id: 56, nameZh: "飞身铲球", nameEn: "Sliding Tackle", description: "提高滑铲的精准度和速度，更容易赢得球权。", descriptionEn: "Performs a Sliding Tackle with greater accuracy and speed, and wins the ball more easily.", categories: ["Defending"], image: "/skills/56.png" },
  { id: 57, nameZh: "伸脚抢截", nameEn: "Long-reach Tackle", description: "静止或缓慢移动时，更频繁地对较远对手施展站立抢断。", descriptionEn: "Increases the frequency of standing tackles, even against far away opponents, while stationary or moving slowly.", categories: ["Showtime"], image: "/skills/57.png" },
  { id: 58, nameZh: "后防领袖", nameEn: "Fortress", description: "下半场领先时提高防守能力。", descriptionEn: "Improves player's defensive abilities after the second half mark, as long as the team has a goal advantage.", categories: ["Showtime"], image: "/skills/58.png" },
  { id: 59, nameZh: "杂技般解围", nameEn: "Acrobatic Clearance", description: "即使姿势不自然，也能用脚解围。", descriptionEn: "Enables the player to clear the ball using his feet, even from awkward positions.", categories: ["Defending"], image: "/skills/59.png" },
  { id: 60, nameZh: "空中堡垒", nameEn: "Aerial Fort", description: "在己方禁区内提高空中对抗能力。", descriptionEn: "Improves player's abilities regarding aerial duels when positioned inside his own penalty box.", categories: ["Showtime"], image: "/skills/60.png" },
  { id: 61, nameZh: "紧急回防", nameEn: "Shadow Hunt", description: "担任后腰或后卫、对手传球打身后时，提高速度相关能力。", descriptionEn: "Increases speed-related abilities when this player is a DMF, RB, LB or CB and an opponent's pass is played behind them.", categories: ["Showtime"], image: "/skills/61.png" },
  { id: 62, nameZh: "队长", nameEn: "Captaincy", description: "成为场上队伍精神支柱，减轻全队疲劳影响。", descriptionEn: "Become the team's inspiration on the pitch, reducing the effects of fatigue for the entire team.", categories: ["Other"], image: "/skills/62.png" },
  { id: 63, nameZh: "进攻号手", nameEn: "Attack Trigger", description: "持球时提高其他队友的进攻意识。", descriptionEn: "Increases all other teammates' Attacking Awareness when this player has control of the ball.", categories: ["Showtime"], image: "/skills/63.png" },
  { id: 64, nameZh: "超级候补", nameEn: "Super-sub", description: "下半场替补登场时提高球员能力。", descriptionEn: "Improves player's abilities when introduced after the second half mark.", categories: ["Other"], image: "/skills/64.png" },
  { id: 65, nameZh: "战斗精神", nameEn: "Fighting Spirit", description: "受到对手压迫时较少损失踢球或头球精准度，也较少受疲劳影响。", descriptionEn: "Rarely loses kicking or heading accuracy when pressured by an opponent, and is less affected by fatigue.", categories: ["Other","Goalkeeping"], image: "/skills/65.png" },
  { id: 66, nameZh: "进攻提速", nameEn: "Attacking Surge", description: "位于进攻半场且队友持球时，提高速度相关能力。", descriptionEn: "Increases speed-related abilities when this player is in the attacking half and a teammate has the ball.", categories: ["Showtime"], image: "/skills/66.png" },
  { id: 67, nameZh: "强力抢断", nameEn: "Power Tackle", description: "使球员更容易施展原地抢断从而通过身体接触赢得球权，同时也更容易通过身体对抗让对手失去平衡。", descriptionEn: "Makes it easier to perform a standing tackle that wins the ball using body contact, while also making it easier to knock the opponent off balance.", categories: ["Showtime"], image: "/skills/67.png" },
];
